kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mini-file-platform
nodes:
  - role: control-plane
    extraPortMappings:
      # Status API exposed on host port 8080
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
