apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-file-platform-config
  namespace: mini-file-platform
data:
  DYNAMODB_TABLE_TRANSACTIONS: "transactions"
  DYNAMODB_ENDPOINT_URL: "http://host.docker.internal:8000"
  S3_RESULTS_BUCKET: "mini-file-platform-results"
  SQS_QUEUE_URL: "${SQS_QUEUE_URL}"
  AWS_DEFAULT_REGION: "us-east-1"
